### ISSUE TITLE
Pull some of the unmerged PRs from main repository

### ISSUE THREAD

**Issue by timrae** [ankidroid/acralyzer#1]
For example this one would be useful... 15 items per page is pretty ridiculous:
https://github.com/ACRA/acralyzer/pull/101

**Comment by agrueneberg** [comment]
Sure, anything else?

**Comment by timrae** [comment]
Thanks! It's not live yet though right?
I think these would all be useful:

https://github.com/ACRA/acralyzer/pull/95
https://github.com/ACRA/acralyzer/pull/96
https://github.com/ACRA/acralyzer/pull/99

**Comment by agrueneberg** [comment]
I pulled all the changes and pushed it out. Let me know if you think that 500 items per page are too sluggish.

**Comment by agrueneberg** [comment]
This is almost too slow for me, should I reduce it to 250?

**Comment by timrae** [comment]
100 would also be fine as the default if that's indeed what's causing the
recent  slowdown. Especially if the global search is done

This is almost too slow for me, should I reduce it to 250?

**Comment by timrae** [comment]
Wow yeah definitely way faster now, thanks for that
