### ISSUE TITLE
Unable to find Chrome OS reports

### ISSUE THREAD

**Issue by agrueneberg** [ankidroid/acralyzer#4]
Either add an option to filter by device, or add ARC to the list of Android versions.

**Comment by agrueneberg** [comment]
I have the suspicion that ACRA (or acra-storage) is swallowing Chrome OS bug reports. Have you ever seen one, @timrae? Will run some tests soon.

**Comment by timrae** [comment]
I've never seen one but:
a) I haven't been looking
b) There will be far less Chrome reports than Android ones so the chance of seeing one are much less

Once the global search is implemented, you should just be able to search for "chromium" (manufacturer) with all attributes check box enabled and they should popup if they're there.

**Comment by timrae** [comment]
Actually that's not true... It would be nice if the search bar supported an attribute specific search syntax. For example:

brand:chromium or build.manufacturer:chrome

**Comment by nicolas-raoul** [comment]
@agrueneberg: As a temporary solution, have you tried searching via Futon?

**Comment by agrueneberg** [comment]
Nevermind, there are a few. I had some data already replicated and ran a temporary view on my local data to not stress out the server.
I like your idea of attribute-specific syntax, @timrae. I don't think this is something we can accomplish with regular CouchDB, but for the global search I'm planning to put Lucene on top of it anyway.
