### ISSUE TITLE
Running very slowly

### ISSUE THREAD

**Issue by timrae** [ankidroid/acralyzer#6]
Acralyzer is running pretty slowly now... Are there any ways to make it more efficient or are we just running into the resource limits of our server?

**Comment by nicolas-raoul** [comment]
What is the load average when it feels slow?
Just run `top` on the server and it will give some first info about load and CPU. Press `m` to sort by memory usage.

**Comment by agrueneberg** [comment]
I restarted CouchDB. The memory consumption jumped back from 390 MB to 140 MB, but it's slowly increasing. The server only has 500 MB, unfortunately. I don't see any errors in the log files. Might be a memory leak. Hard to tell.
